
###################################################
# This file was autogenerated by notebook2script. #
# Edit 02_fully_connected.ipynb instead.                      #
###################################################
def get_data():
    path = datasets.download_data(MNIST_URL, ext='.gz')

    with gzip.open(path, 'rb') as f:
        ((x_train, y_train), (x_valid, y_valid), _) = pickle.load(f, encoding='latin-1')

    return map(tensor, (x_train, y_train, x_valid, y_valid))


def normalize(x, mu, sig): return (x - mu) / sig

def test_near_zero(a, tol=1e-3): assert a.abs() < tol, f'Not near-zero: {a}'

from torch.nn import init